name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile-de-proxy/wrangler-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          MOBILEDE_USERNAME: ${{ secrets.MOBILEDE_USERNAME }}
          MOBILEDE_PASSWORD: ${{ secrets.MOBILEDE_PASSWORD }}
        run: |
          npm i wrangler
          npx wrangler deploy
          npx wrangler secret put MOBILEDE_USERNAME <<< "$MOBILEDE_USERNAME"
          npx wrangler secret put MOBILEDE_PASSWORD <<< "$MOBILEDE_PASSWORD"

  deploy-site:
    needs: deploy-worker
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2